version: '3.4'

services:
  fiverr:
    image: fiverr
    build:
      context: Fiverr
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
